version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: vault_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootSuperSecretPassword! 
      MYSQL_DATABASE: memory_vault
      MYSQL_USER: vault_user
      MYSQL_PASSWORD: vault_password123 
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: vault_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=vault_user
      - DB_PASSWORD=vault_password123
      - DB_NAME=memory_vault
    depends_on:
      - db

volumes:
  dbdata: